name: Bug Report
description: There is a problem with swaydots
title: "[Bug] "
labels: ["bug"]
assignees:
  - aceydot

body:
  - type: checkboxes
    attributes:
      label: Bug already been reported?
      description: Before submitting a new bug report, please check if a similar issue is already open.
      options:
      - label: There isn't a similar open issue.
        required: true
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What went wrong?"
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: "System information"
      description: |
        Please provide your system details.  
        Run `inxi --full` (install with `sudo pacman -S inxi` if not available) and paste the output below.
      value: |
        ```bash
        # Paste the output of `inxi --full` here
        ```
    validations:
      required: true

  - type: textarea
    id: reproducing
    attributes:
      label: How to reproduce
      description: "How can we reproduce the issue?"
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Logs or media
      description: |
        Attach any logs or media that can help solve this bug.

