name: Request
description: I want to add something to swaydots
title: "[Request] "
labels: ["request"]
assignees:
  - aceydot

body:
  - type: checkboxes
    attributes:
      label: Request already been submitted?
      description: Before creating a new request, please check if a similar one is already open.
      options:
      - label: There isn't a similar request open.
        required: true

  - type: dropdown
    id: type
    attributes:
      label: What do you want to add?
      options:
        - "Feature"
        - "Theme"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Explain what you want to add."
    validations:
      required: true
      
  - type: textarea
    id: implement
    attributes:
      label: How?
      description: "How do you think we should implement it?"
    validations:
      required: true

