name: Wiki
description: Suggest a update to the swaydots wiki.
title: "[Wiki] "
labels: ["wiki"]
assignees:
  - aceydot

body:
  - type: checkboxes
    attributes:
      label: Update already proposed?
      description: Before submitting a new update proposal, please check if a similar one is already open.
      options:
      - label: There isn't a similar update proposal open.
        required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What needs to be updated/added?"
    validations:
      required: true

